import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Amberly - Free movies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " dark"}>
        {children}
        <Toaster
          toastOptions={{
            unstyled: true,
            classNames:{
              error: 'bg-red-600 p-5 rounded-md w-full flex items-center space-x-4',
              success: 'bg-green-600 p-5 rounded-md w-full flex items-center space-x-4',
              warning: 'bg-yellow-600 p-5 rounded-md w-full flex items-center space-x-4'
            }
          }}
        />
      </body>
    </html>
  );
}
